from pydantic import BaseModel, EmailStr

# Schema for creating user ( what client sends )
# Basically what user SENDS to create , there no ID for now, it will be generated by the database
class UserCreate(BaseModel):
    name:str
    email: EmailStr
    age: int

# Schema for returning user ( what API returns )
class UserResponse(BaseModel):
    id: int # <- Database added this in the model 
    name: str
    email: str
    age: int

    """
    This tells pydantic that accept SQLAlchemy models, allows UserResponse.from_orm(db_user)
    Converts database object -> Pydantic model
    """
    class Config: 
        from_attributes = True